apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi-nas
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.9.79
  share: /volume1/PV-Test
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1
  - hard